sudo: required
language: go
go: 1.6

before_install:
  - curl -ko /tmp/kapacitor.deb https://dl.influxdata.com/kapacitor/releases/kapacitor_0.13.1_amd64.deb
  - sudo dpkg -i /tmp/kapacitor.deb
  - curl -ko /tmp/influxdb.deb https://dl.influxdata.com/influxdb/releases/influxdb_0.13.0_amd64.deb
  - sudo dpkg -i /tmp/influxdb.deb
  - sudo service influxdb start
  - sudo service kapacitor start
install: go get -t -v .
script: go test -v -cover ./...
